---
- name: Deploy Calculator App with Docker
  hosts: webserver
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Pull the latest Docker image
      community.docker.docker_image:
        name: tushar542001/scientific-calculator:latest
        source: pull

    - name: Stop and remove existing container (if any)
      community.docker.docker_container:
        name: scientific-calculator
        state: absent

    - name: Run new container
      community.docker.docker_container:
        name: scientific-calculator
        image: tushar542001/scientific-calculator:latest
        state: started
        restart_policy: always
        interactive: true
        tty: true
        command: "java -jar /app/scientific-calculator.jar"
